name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle 9.3.1
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '9.3.1'

      - name: Build Release APK
        run: gradle assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: app/build/outputs/apk/release/*.apk
